// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"database/sql"
	"time"
)

type Transaction struct {
	ID        int32
	UserID    sql.NullInt32
	Amount    float64
	Type      string
	CreatedAt time.Time
}

type User struct {
	ID        int32
	Username  string
	Password  string
	Balance   float64
	CreatedAt time.Time
}
