// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: transaction.sql

package postgres

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, type, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id
`

type CreateTransactionParams struct {
	UserID sql.NullInt32
	Amount float64
	Type   string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, arg.UserID, arg.Amount, arg.Type)
	var id int32
	err := row.Scan(&id)
	return id, err
}
